DESCRIBE JOBS;

SELECT *
FROM JOBS;

SELECT JOB_ID,MIN_SALARY,MAX_SALARY
FROM JOBS;


SELECT JOB_ID, (MAX_SALARY + MIN_SALARY) AS “diferenta”
FROM JOBS;

DESCRIBE EMPLOYEES;

SELECT *
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES;

SELECT LAST_NAME || ', ' || JOB_ID AS "Angajat si titlu"
FROM EMPLOYEES;

SELECT
EMPLOYEE_ID||','||FIRST_NAME||','||LAST_NAME||','||EMAIL||','||PHONE_NUMBER||','||HIRE_DATE||','||JOB_ID||','||SALARY||','||
COMMISSION_PCT||','||MANAGER_ID||','||DEPARTMENT_ID AS "Informatii complete"
FROM EMPLOYEES;

SELECT SYSDATE 
FROM DUAL;

SELECT TO_CHAR(SYSDATE,’MONTH’)
FROM DUAL;

SELECT 2+3 AS “SUMA” 
FROM DUAL;

SELECT 
FIRST_NAME,SALARY AS "si"
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT 
FIRST_NAME,SALARY 
FROM EMPLOYEES
ORDER BY 1 DESC;

SELECT 
FIRST_NAME,SALARY AS "s1"
FROM EMPLOYEES
ORDER BY "s1" DESC;

SELECT SYSDATE
FROM
EMPLOYEES;

SELECT TO_CHAR(SYSDATE,'DD/MM/YYY HH24:MI') AS "DATAA"
FROM DUAL;

SELECT EMPLOYEE_ID, FIRST_NAME, TO_CHAR(HIRE_DATE, 'D')
FROM EMPLOYEES;

SELECT FIRST_NAME , TO_CHAR(HIRE_DATE,'YYY')
FROM EMPLOYEES
ORDER BY TO_CHAR(HIRE_DATE,'YYY'),TO_CHAR(HIRE_DATE,'DD');

SELECT FIRST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY >2850;

SELECT FIRST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (10,30,50)
ORDER BY FIRST_NAME;

SELECT FIRST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '20-Februarie-1987' AND '1-Mai-1989';

SELECT FIRST_NAME, JOB_ID;
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

DESCRIBE JOBS;



